baseurl = "/mongo-csharp-driver/2.2"
languageCode = "en-us"
title = "MongoDB .NET Driver"
theme = "mongodb"
canonifyurls = false

[blackfriday]
  plainIdAnchors = true

[[menu.main]]
    name = "API Documentation"
    pre = "<i class='fa fa-file-text-o'></i>"
    weight = 800
    identifier = "apiDocs"
    url = "http://api.mongodb.org/csharp/2.2"

[[menu.main]]
    name = "Source Code"
    pre = "<i class='fa fa-github'></i>"
    weight = 900
    identifier = "githubLink"
    url = "https://github.com/mongodb/mongo-csharp-driver/tree/master"